### ISSUE TITLE
Add android:exported="false" to AndroidManifest activity

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitytoolkit.metaplatform#25]
Starting with Unity 2022 Android builds will not build correctly if the manifest does not explicitly define the `android:exported` property.

**Comment by SimonDarksideJ** [comment]
And let me guess @FejZa , Unity doesn't include this in their autogenerated manifest, or is this something that affects the Android manifest we generate for Quest?

**Comment by FejZa** [comment]
This was a bug in an earlier 2022 Unity build that was resolved by Unity in the meantime.
