### ISSUE TITLE
Meta Touch Controller input mapping is not understandable

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitytoolkit.metaplatform#3]
# Reality Toolkit Bug Report

## Describe the bug

The input mapping for Meta Touch controllers is very cryptic and one does not understand what mapping belongs to what button the controller.

![image](https://user-images.githubusercontent.com/9565734/152952045-88146842-e1e2-49c9-93e1-b41080ae04c9.png)

**Comment by SimonDarksideJ** [comment]
Will reopen in the .dev project
